version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:8080"
    
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
